### ISSUE TITLE
Error for France

### ISSUE THREAD

**Issue by hugrowth** [metalwarrior665/actor-indeed-scraper#4]
I think it's not working with "France" as country... 

This error message appears, what could I do ? 

`ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.indeed.fr/jobs?q=Growth&l=Paris","retryCount":4,"id":"OeKkimKxrTiYXG2"}
2020-11-24T19:24:43.735Z   MaxRedirectsError: Redirected 10 times. Aborting.
2020-11-24T19:24:43.737Z       at ClientRequest.handleResponse (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:128:14)
2020-11-24T19:24:43.739Z       at Object.onceWrapper (events.js:422:26)
2020-11-24T19:24:43.740Z       at ClientRequest.emit (events.js:327:22)
2020-11-24T19:24:43.742Z       at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
2020-11-24T19:24:43.744Z       at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
2020-11-24T19:24:43.746Z       at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
2020-11-24T19:24:43.748Z       at TLSSocket.socketOnData (_http_client.js:469:22)
2020-11-24T19:24:43.750Z       at TLSSocket.emit (events.js:315:20)
2020-11-24T19:24:43.752Z       at addChunk (_stream_readable.js:295:12)
2020-11-24T19:24:43.754Z       at readableAddChunk (_stream_readable.js:271:9)
2020-11-24T19:24:43.756Z       at TLSSocket.Readable.push (_stream_readable.js:212:10)
2020-11-24T19:24:43.758Z       at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)`

**Comment by zpelechova** [comment]
Ia m testing it on France and it is working can you recheck?
